on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-frontend:
    defaults:
      run:
        working-directory: city-list-frontend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: city-list-frontend/package-lock.json
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@master
        with:
          name: frontend-build
          path: city-list-frontend/build/**/*