on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Clean Test Package with Maven
      run: mvn clean package
