on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-backend:
    runs-on: ubuntu-latest
    needs: ["build-frontend" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - uses: actions/download-artifact@master
        with:
          name: frontend-build
          path: frontend-build
      - run: mkdir src/main/resources/static
      - run: cp -r frontend-build/* src/main/resources/static/
      - name: Package with Maven
        run: mvn package
      - uses: actions/upload-artifact@master
        with:
          name: backend-build
          path: target/city-list-backend-0.0.1-SNAPSHOT.jar