on:
  workflow_run:
    workflows: ["build-backend","build-frontend"]
    types:
      - completed
    branches: ["*"]
jobs:
  package-frontend-with-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: backend-build
          path: backend-build
      - uses: actions/download-artifact@master
        with:
          name: frontend-build
          path: frontend-build
      - run: ls frontend-build
      - run: ls backend-build
